// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: gmail-service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Email struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Email) Reset() {
	*x = Email{}
	mi := &file_gmail_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_gmail_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_gmail_service_proto_rawDescGZIP(), []int{0}
}

func (x *Email) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type EmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           string                 `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailResponse) Reset() {
	*x = EmailResponse{}
	mi := &file_gmail_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailResponse) ProtoMessage() {}

func (x *EmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gmail_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailResponse.ProtoReflect.Descriptor instead.
func (*EmailResponse) Descriptor() ([]byte, []int) {
	return file_gmail_service_proto_rawDescGZIP(), []int{1}
}

func (x *EmailResponse) GetRes() string {
	if x != nil {
		return x.Res
	}
	return ""
}

var File_gmail_service_proto protoreflect.FileDescriptor

const file_gmail_service_proto_rawDesc = "" +
	"\n" +
	"\x13gmail-service.proto\x12\x05proto\"\x1d\n" +
	"\x05Email\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"!\n" +
	"\rEmailResponse\x12\x10\n" +
	"\x03res\x18\x01 \x01(\tR\x03res2A\n" +
	"\fGmailService\x121\n" +
	"\tsendEmail\x12\f.proto.Email\x1a\x14.proto.EmailResponse\"\x00B\x06Z\x04./pbb\x06proto3"

var (
	file_gmail_service_proto_rawDescOnce sync.Once
	file_gmail_service_proto_rawDescData []byte
)

func file_gmail_service_proto_rawDescGZIP() []byte {
	file_gmail_service_proto_rawDescOnce.Do(func() {
		file_gmail_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gmail_service_proto_rawDesc), len(file_gmail_service_proto_rawDesc)))
	})
	return file_gmail_service_proto_rawDescData
}

var file_gmail_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gmail_service_proto_goTypes = []any{
	(*Email)(nil),         // 0: proto.Email
	(*EmailResponse)(nil), // 1: proto.EmailResponse
}
var file_gmail_service_proto_depIdxs = []int32{
	0, // 0: proto.GmailService.sendEmail:input_type -> proto.Email
	1, // 1: proto.GmailService.sendEmail:output_type -> proto.EmailResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gmail_service_proto_init() }
func file_gmail_service_proto_init() {
	if File_gmail_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gmail_service_proto_rawDesc), len(file_gmail_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gmail_service_proto_goTypes,
		DependencyIndexes: file_gmail_service_proto_depIdxs,
		MessageInfos:      file_gmail_service_proto_msgTypes,
	}.Build()
	File_gmail_service_proto = out.File
	file_gmail_service_proto_goTypes = nil
	file_gmail_service_proto_depIdxs = nil
}
