// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: gmail-service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GmailService_SendEmail_FullMethodName = "/proto.GmailService/sendEmail"
)

// GmailServiceClient is the client API for GmailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GmailServiceClient interface {
	SendEmail(ctx context.Context, in *Email, opts ...grpc.CallOption) (*EmailResponse, error)
}

type gmailServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGmailServiceClient(cc grpc.ClientConnInterface) GmailServiceClient {
	return &gmailServiceClient{cc}
}

func (c *gmailServiceClient) SendEmail(ctx context.Context, in *Email, opts ...grpc.CallOption) (*EmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmailResponse)
	err := c.cc.Invoke(ctx, GmailService_SendEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GmailServiceServer is the server API for GmailService service.
// All implementations must embed UnimplementedGmailServiceServer
// for forward compatibility.
type GmailServiceServer interface {
	SendEmail(context.Context, *Email) (*EmailResponse, error)
	mustEmbedUnimplementedGmailServiceServer()
}

// UnimplementedGmailServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGmailServiceServer struct{}

func (UnimplementedGmailServiceServer) SendEmail(context.Context, *Email) (*EmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendEmail not implemented")
}
func (UnimplementedGmailServiceServer) mustEmbedUnimplementedGmailServiceServer() {}
func (UnimplementedGmailServiceServer) testEmbeddedByValue()                      {}

// UnsafeGmailServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GmailServiceServer will
// result in compilation errors.
type UnsafeGmailServiceServer interface {
	mustEmbedUnimplementedGmailServiceServer()
}

func RegisterGmailServiceServer(s grpc.ServiceRegistrar, srv GmailServiceServer) {
	// If the following call panics, it indicates UnimplementedGmailServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GmailService_ServiceDesc, srv)
}

func _GmailService_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Email)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GmailServiceServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GmailService_SendEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GmailServiceServer).SendEmail(ctx, req.(*Email))
	}
	return interceptor(ctx, in, info, handler)
}

// GmailService_ServiceDesc is the grpc.ServiceDesc for GmailService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GmailService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GmailService",
	HandlerType: (*GmailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sendEmail",
			Handler:    _GmailService_SendEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gmail-service.proto",
}
