// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: shared/proto/workflow.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TriggerRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	// JSON payload representing the initial data (e.g., webhook body)
	InitialPayload string `protobuf:"bytes,2,opt,name=initial_payload,json=initialPayload,proto3" json:"initial_payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TriggerRequest) Reset() {
	*x = TriggerRequest{}
	mi := &file_shared_proto_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRequest) ProtoMessage() {}

func (x *TriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRequest.ProtoReflect.Descriptor instead.
func (*TriggerRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *TriggerRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *TriggerRequest) GetInitialPayload() string {
	if x != nil {
		return x.InitialPayload
	}
	return ""
}

type TriggerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerResponse) Reset() {
	*x = TriggerResponse{}
	mi := &file_shared_proto_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerResponse) ProtoMessage() {}

func (x *TriggerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerResponse.ProtoReflect.Descriptor instead.
func (*TriggerResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *TriggerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskName      string                 `protobuf:"bytes,1,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,2,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	InputPayload  string                 `protobuf:"bytes,3,opt,name=input_payload,json=inputPayload,proto3" json:"input_payload,omitempty"`
	AuthToken     string                 `protobuf:"bytes,4,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_shared_proto_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *TaskRequest) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *TaskRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *TaskRequest) GetInputPayload() string {
	if x != nil {
		return x.InputPayload
	}
	return ""
}

func (x *TaskRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	OutputPayload string                 `protobuf:"bytes,2,opt,name=output_payload,json=outputPayload,proto3" json:"output_payload,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_shared_proto_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *TaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResponse) GetOutputPayload() string {
	if x != nil {
		return x.OutputPayload
	}
	return ""
}

func (x *TaskResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_shared_proto_workflow_proto protoreflect.FileDescriptor

const file_shared_proto_workflow_proto_rawDesc = "" +
	"\n" +
	"\x1bshared/proto/workflow.proto\x12\bworkflow\"Z\n" +
	"\x0eTriggerRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12'\n" +
	"\x0finitial_payload\x18\x02 \x01(\tR\x0einitialPayload\"N\n" +
	"\x0fTriggerResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\x8f\x01\n" +
	"\vTaskRequest\x12\x1b\n" +
	"\ttask_name\x18\x01 \x01(\tR\btaskName\x12\x1f\n" +
	"\vconfig_json\x18\x02 \x01(\tR\n" +
	"configJson\x12#\n" +
	"\rinput_payload\x18\x03 \x01(\tR\finputPayload\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x04 \x01(\tR\tauthToken\"t\n" +
	"\fTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0eoutput_payload\x18\x02 \x01(\tR\routputPayload\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage2V\n" +
	"\fOrchestrator\x12F\n" +
	"\x0fTriggerWorkflow\x12\x18.workflow.TriggerRequest\x1a\x19.workflow.TriggerResponse2J\n" +
	"\n" +
	"TaskWorker\x12<\n" +
	"\vExecuteTask\x12\x15.workflow.TaskRequest\x1a\x16.workflow.TaskResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_shared_proto_workflow_proto_rawDescOnce sync.Once
	file_shared_proto_workflow_proto_rawDescData []byte
)

func file_shared_proto_workflow_proto_rawDescGZIP() []byte {
	file_shared_proto_workflow_proto_rawDescOnce.Do(func() {
		file_shared_proto_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_workflow_proto_rawDesc), len(file_shared_proto_workflow_proto_rawDesc)))
	})
	return file_shared_proto_workflow_proto_rawDescData
}

var file_shared_proto_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shared_proto_workflow_proto_goTypes = []any{
	(*TriggerRequest)(nil),  // 0: workflow.TriggerRequest
	(*TriggerResponse)(nil), // 1: workflow.TriggerResponse
	(*TaskRequest)(nil),     // 2: workflow.TaskRequest
	(*TaskResponse)(nil),    // 3: workflow.TaskResponse
}
var file_shared_proto_workflow_proto_depIdxs = []int32{
	0, // 0: workflow.Orchestrator.TriggerWorkflow:input_type -> workflow.TriggerRequest
	2, // 1: workflow.TaskWorker.ExecuteTask:input_type -> workflow.TaskRequest
	1, // 2: workflow.Orchestrator.TriggerWorkflow:output_type -> workflow.TriggerResponse
	3, // 3: workflow.TaskWorker.ExecuteTask:output_type -> workflow.TaskResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_proto_workflow_proto_init() }
func file_shared_proto_workflow_proto_init() {
	if File_shared_proto_workflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_workflow_proto_rawDesc), len(file_shared_proto_workflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_shared_proto_workflow_proto_goTypes,
		DependencyIndexes: file_shared_proto_workflow_proto_depIdxs,
		MessageInfos:      file_shared_proto_workflow_proto_msgTypes,
	}.Build()
	File_shared_proto_workflow_proto = out.File
	file_shared_proto_workflow_proto_goTypes = nil
	file_shared_proto_workflow_proto_depIdxs = nil
}
