CREATE TABLE workflows (
    id AUTO_INCREMENT PRIMARY KEY,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    name VARCHAR(255) NOT NULL,
    active BOOLEAN DEFAULT FALSE,
    user_id INT DEFAULT 0 -- Only system user for now
);